<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="./assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="./assets/css/search_agent.css">
    <link rel="icon" type="text/css" href="./assets/img/favicon-128.png">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
  </head>
  <body>
    <section class="privacy_policy">
      <div class="wrapper">
        <div class="row p-0 m-0">
          <!-- Header Start -->
          <?php include 'header_navbar.php'; ?>
          <!-- Nav end -->
          <div class="col-12 d-flex justify-content-end mt-4 p-0"><a href="privacy_policy.php" class="a_color text-decoration-underline" title="To the English version">Our privacy policy in German</a></div>
          <div class="col-12 d-flex justify-content-end p-0"><a href="terms_condition.php" class="a_color text-decoration-underline" title="To the terms and conditions">View Terms and Conditions</a></div>
          <div class="col-12 d-flex justify-content-end mb-3 p-0"><a href="imprint.php" class="a_color text-decoration-underline" title="To the imprint">To the imprint</a></div>
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ps-3 pe-0">
            <h5>Privacy Policy</h5>
            
            <h6>1. General Information</h6>
            <p>This Privacy Policy is intended to explain to you the nature, scope and purpose of the way we process personal data ("data") in connection with our online platform and the web pages, functions and content associated with it, as well as through our external online presence, such as social media profiles (hereinafter commonly known as the "website"). Regarding the terms used, such as 'processing" or 'controller", we refer to the definitions provided in Art. 4 of the General Data Protection Regulation (GDPR). </p>
            <h6>2. Protection of personal data </h6>
            <p>We (FindMyHome.at GmbH, FN 254125p) will only process your personal data if you have issued consent, or in order to fulfil your instructions/inquiry or purchase order for the purposes agreed with you, or if another legal basis exists for doing so (as defined in the GDPR). We will only collect that personal data necessary for the performance and settlement of our activities and services, along with that data you have provided to us voluntarily.</p>
            <p>We will only process additional personal data if you have provided us with your personal data voluntarily, such as when you get in contact with us. In this case, we will use your personal data in order to process your inquiries, for technical processing purposes (administration) and for the examination and possible enforcement of our claims against our contractual partners.</p>
            <p>Personal data is deemed to be such information, based on which a person is clearly identifiable. This includes name, email address and telephone number as well as the IP address of the user and, where relevant, its domain name and the name of your internet service provider.</p>
            <h6>3. Your right to access and erasure (rights of data subjects)</h6>
            <p>You have the right to information concerning your personal data that is stored by us, the source and recipients of this data, and the purpose of the data processing as well as the right to rectification, blocking or erasure of inaccurate/impermissible processed data.</p>
            <p>You have the right at any time to withdraw any consent you have already issued regarding the use of your personal data. To assert your rights as a data subject (right to information, erasure, correction, objection and/or data portability), simply contact datenschutz@findmyhome.at.</p>
            <p>If you are of the opinion that the processing of your personal data by us, is in breach of data protection law, or your data protection entitlements are being infringed in another way, you have the option of lodging a complaint with the competent supervisory authority. In Austria, this is the data protection authorities.</p>
            <h6>4. Use of data - security </h6>
            <p>We are a real estate platform, and as such we also facilitate contacts between potential customers, property suppliers, real estate agents and cooperation partners. These include removal companies, providers of internet, TV and landline telephony services, as well as mobile phone providers, locality checking companies, expert brokers for the sale of property, as well as other service companies covering all aspects of residential property. For that reason, certain personal data needed by the users of our real estate platform for the purpose of establishing business contact with one another, will be passed on (as well as stored, processed and/or transferred).</p>
            <p>This data concerns the details and information to be provided in connection with the use of our services, and/or information voluntarily provided by you. The data provided to us will not be processed for any purposes other than those encompassed by your consent, or by a provision according to the GDPR. As an exception to this, data may be used for statistical purposes, provided the supplied data has been rendered anonymous. In any case, the processing is carried out to examine and enforce our possible claims/ premiums. Where we intend to further process your personal data for a purpose other than that for which the personal data was collected, prior to that further processing we shall provide you with information on that other purpose and with any relevant further information as referred to in Art. 13 Abs. 2 GDPR.</p>
            <p>As part of our quality programms, agents and providers will be rated by our users for the purpose of enhancing quality and to serve as a guide. For this purpose, we will collect or obtain an emailed user rating of the services of the agents and providers. The agents and providers have agreed to participate in this quality programme. Users provide ratings voluntarily. This data is processed exclusively in connection with the quality programme.</p>
            <p>We have implemented state-of-the-art organisational and technical safeguards to ensure the protection of your personal data (protection against misuse, but internally and externally), such as through firewalls, encryption measures, access permissions etc.). However, it cannot be ruled out that errors in the data transfer, over which we have no control, or authorised intrusions by third parties (hacker etc.) will result in other individuals viewing or using such information. We accept no liability in this instance, provided we are not culpable of causing the misuse. There is, of course, the option of using regular post in connection with the use or processing of highly sensitive data or information, because it is impossible to achieve absolute security for email correspondence.</p>
            <h6>5. Transfer of data to third parties (transmission)</h6>
            <p>We do not make your personal data available to others, except in those instances described in Number 4. However, it is necessary to transfer your data to third parties for the fulfilment of your contract or for legal reasons. This may relate to courts or public authorities or other third parties involved in the process. Third parties include processors (IT consultants, external software partners and data suppliers and processors) engaged on our behalf. However, this will only take place to the smallest extent necessary, and only insofar as it is necessary for the further processing of your inquiry and usage. In this case, your data will be transferred solely on the basis of the GDPR (on the basis of your consent, fulfilment of a contract, fulfilment of a legal obligation, etc.).</p>
            <p>Please also note that we may have to transmit your personal data to recipients (see above) located outside of your country. However, we will only transfer your personal data exclusively on the basis of the GDPR (adequate level of data protection, and the implementation of measures to ensure that all recipients maintain an adequate level of data protection).</p>
            <h6>6. Storage/erasure of data</h6>
            <p>The data processed by us will be erased or the processing restricted in accordance with Art. 17 and 18 GDPR. Unless otherwise explicitly stated in this Privacy Policy, we will erase stored data when it is no longer needed for the designated purpose, and the erasure is not blocked by any contrary statutory data retention obligations. If the data is not erased, because it is needed for other legally permissible purposes, the processing will be restricted. This means that the data will be blocked and not used for any other purposes. This applies, for example, to data that must be retained in accordance with commercial and tax regulations.</p>
            <h6>7. Cookies</h6>
            <p>Our website uses cookies. The use of cookies is necessary for us to offer you our services in full, to improve your user experience, and to improve our quality and our service.</p>
            <p>Cookies are small text files that are stored on the user's terminal device. Cookies can store a range of data. The main purpose of a cookie is to store data concerning a user (or the device on which the cookie is stored) during and also after his or her website visit.
            Temporary cookies, also known as 'session cookies" or "transient cookies" are cookies that are deleted once the user has exited the website and closes their browser. This type of cookies can store a login status for example. 'Permanent" or 'persistent" cookies are those which remain stored even after the browser has been closed. For example, it enables a login status to be stored, when users visit the site again after a period of several days. This type of cookie can also store user interests, which are used for the range measurement and marketing purposes. "Third-party cookies" are those used by providers other than the controller operating the website (cookies used by the latter are called "first-party cookies").</p>
            <p>We may use temporary and permanent cookies, and their use is explained in our Privacy Policy.
            If you do not want cookies to be stored on your computer you may deactivate the relevant option in your browser settings. Cookies stored on your computer can erased using the system settings of the browser. Blocking cookies may reduce the functions and user experience of our website.</p>
            <p>It is possible to generally block cookies used for online marketing purposes with the majority of services, but particularly in the case of tracking. This can be done via the U.S. web page <a href="#" class="a_color text-decoration-underline" target="_blank">https://www.aboutads.info/choices/</a> or the EU page <a href="#" class="a_color text-decoration-underline" target="_blank">https://www.youronlinechoices.com/.</a> Furthermore, the storage of cookies can be prevented by deactivating them in the browser settings. Please note that in this case not all functions of this online site will be available.</p>
            <h6>8. Web analysis/server log files</h6>
            <p>For the purpose of our legitimate interest within the definition of Art. 6 Abs. 1 lit. f. GDPR, we, or our host provider, collect data each time the server on which the service is located is accessed ("server log files"). This access data includes the name of the web page and/or file accessed by the user, the date and time of access, the amount of data transferred, notification of successful retrieval, details of the web browser used including the applicable version, the user's operating system, the referrer URL (of the previous page linking to our website), the IP address and the requesting provider.</p>
            <p>Log file information is retained for security reasons (e.g. to detect misuse or fraud), and for the purpose of optimising the website in relation to user-friendliness and for providing useful information regarding our services. This data will not be merged with personal data sources.</p>
            <h6>9. Google Analytics</h6>
            <p>For the purpose of our legitimate interests (i.e. our interest in analysing, optimising and running our online platform in a commercially viable manner within the meaning of Art. 6 (1) point f) GDPR), we use Google Analytics, a web analysis service provided by Google LLC ('Google").</p>
            <p>Google used cookies. The information generated by the cookie regarding website use will normally be transmitted to a Google server in the United States and stored there. Google is certified under the Privacy Shield framework which guarantees compliance with European data protection legislation (<a href="#" class="a_color text-decoration-underline" target="_blank">https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active</a>). Google will use this information on our behalf for the purpose of evaluating use of our website by the user, compiling reports on activity on the Websites, and providing us with other services relating to the use of the Websites and use of the internet. . This process may involve creating pseudonymised usage profiles of users from the processed data. We only use Google Analytics with IP anonymisation enabled. That means Google truncates the user's IP address within Member States of the European Union and in other countries that are party to the Agreement on the European Economic Area. Only in exceptional cases will the complete IP address be sent to a Google server in the United States and truncated there. The IP address relayed by the user's browser within the Google Analytics process will not be linked to any other data owned by Google.</p>
            <p>Users can prevent cookies from being installed on their computer by adjusting their browser settings accordingly. Users can also prevent Google from collecting data generated by cookies concerning their use of the Websites and can prevent Google from processing this data by downloading and installing a browser plug-in from the following link: <a href="#" class="a_color text-decoration-underline" target="_blank">https://tools.google.com/dlpage/gaoptout?hl=de</a>.</p>
            <p>For more information on how Google uses data and how to opt out and configure your settings, please read Google's Privacy Policy (https://policies.google.com/technologies/ads) and the settings for ads displayed by Google (<a href="#" class="a_color text-decoration-underline" target="_blank">https://adssettings.google.com/authenticated</a>). The user"s personal data will be deleted or rendered anonymous after 14 months.</p>
            <h6>10. Google (re)marketing services</h6>
            <p>For the purpose of our legitimate interests (our interest in analysing, optimising and running our website in a commercially viable manner within the meaning of Art. 6 (1) point f) GDPR), we use the marketing and remarketing services (hereinafter referred to as 'Google marketing services") provided by Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA, ('Google").</p>
            <p>Google is certified under the Privacy Shield framework which guarantees compliance with European data protection legislation (<a href="#" class="a_color text-decoration-underline" target="_blank">https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active</a>). Google marketing services enable us to display ads for and on our website in a more targeted fashion, helping us to only show users those ads that are potentially of interest to them. We use remarketing methods, which, for example, includes showing users ads for products in which they have already shown an interest on other websites. For this purpose, our website, and other websites on which Google marketing services are activated, contain a code element, which is executed directly by Google. This integrates what are known as (re)marketing tags in the website (invisible image files or code, also known as "web beacons'). With the help of these tags, an individual cookie, i.e. a small file, is saved to the user's device (comparable technologies can also be applied instead). These cookies may originate from various domains, including google.com, doubleclick.net, invitemedia.com, admeld.com, googlesyndication.com and googleadservices.com. This file notes which sites the user visits, which content interests the user, and which offers he or she clicked, as well as technical information on the browser and operating system, referring websites, visit duration and other data on the use of the Websites.</p>
            <p>The user's IP address is also recorded, though please note, within the context of Google Analytics, the IP address is truncated within European Union Member States and in other countries that are party to the Agreement on the European Economic Area. The IP address is not merged with User data within other Google services.</p>
            <p>The information referred to above may also be linked by Google to equivalent information from other sources. If the user subsequently visits other websites, they may be presented with ads tailored to them based on their interests. User data is processed in a pseudonymised manner within the context of Google marketing services. This means that Google does not store and process details such as the name or email address of the user, but instead processes the relevant data within pseudonymised usage profiles based on cookies. So for Google's purposes, the ads are not administered for and displayed to a named or otherwise identifiable person, but rather for and to the cookie holder, regardless of who this cookie holder is. That is not, however, the case if a User explicitly permits Google to process their data in a non-pseudonymised manner. Information collected on users by Google marketing services is transmitted to Google and stored on Google's servers located in the USA. One of the Google marketing services we use is the online advertising service 'Google AdWords".</p>
            <p>With Google AdWords, each AdWords client receives a different "conversion cookie". This means that cookies cannot be tracked across the websites of AdWords clients. The information collected by the conversion cookies is used to provide aggregate conversion statistics for AdWords clients who have opted in to conversion tracking. AdWords clients are notified about the total number of users who clicked on the ad and who were forwarded to a conversion tracking tag page. However, they do not receive any information that would enable them to identify users personally.</p>
            <p>We may include third-party advertisements by using the Google Marketing Service 'AdSense". AdSense uses cookies to enable Google and its partner sites to display ads based on users' visits to this site or other sites on the internet. We may also 'Google Tag Manager" to integrate and manage Google analysis and marketing services into our website.</p>
            <p>Further information on Google's use of data for marketing purposes can be found in the following summary: <a class="a_color text-decoration-underline" href="https://www.google.com/policies/technologies/ads" target="_blank">https://www.google.com/policies/technologies/ads</a>; Google"s Privacy Policy is available at <a class="a_color text-decoration-underline" href="https://www.google.com/policies/privacy" target="_blank">https://www.google.com/policies/privacy</a>. If you wish to block interest-based advertising by Google marketing services, you can use the setting and opt-out options provided by Google: <a class="a_color text-decoration-underline" href="https://www.google.com/ads/preferences" target="_blank">https://www.google.com/ads/preferences</a>.
            <h6>11. Online social media platforms</h6>
            <p>We maintain an online presence in social networks and platforms, in order to communicate with customers, potential customers and user"s active there, and to tell them about our online platform and services. By visiting these networks and platforms, as well as when linking to other websites, the terms and conditions and data privacy policies of the relevant operators shall apply respectively.</p>
            <p>Unless otherwise stated in our Privacy Policy, we will process the data of users who communicate with us in social networks and platforms, for example, who post comments on our online site or send us messages.</p>
            <h6>12. Integration of third-party services and content</h6>
            <p>For the purposes of our legitimate interests (i.e. our interest in analysing, optimising and running our website in a commercially viable manner within the meaning of Art. 6 (1) point f) GDPR), we use third-party content and service delivery services on our website in order to incorporate content and services such as videos and fonts, for example (hereinafter jointly referred to as "content").</p>
            <p>The third-party provider of this content always requires the user's IP address in order to send the content to the browser of the respective user. The IP address is therefore required in order to display such content. We make every effort to only use that content whereby the providers in question only use the IP address for the purpose of delivering the content. Third parties may use "pixel tags" (hidden graphics, also known as "web beacons") for statistical or marketing purposes.</p>
            <p>These pixel tags can be used to evaluate information such as visitor traffic accessing the pages on this website. The pseudonymised information may be stored in cookies on the user's device and may include, but is not limited to, technical information about the browser and operating system, referrer web pages, visit time, and other information regarding the use of our online site.</p>
            <p>Facebook Pixel, Custom Audiences and Facebook Conversion</p>
            <p>For the purpose of our legitimate interests in analysing, optimising and running our website in a commercially viable manner, our website incorporates provided by the social network Facebook, run by Facebook Inc., 1 Hacker Way, Menlo Park, CA 94025, USA, or, for those based in Europe, by Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland('Facebook") Facebook is certified under the Privacy Shield framework which guarantees compliance with European data protection legislation (<a class="a_color text-decoration-underline" href="https://www.privacyshield.gov/participant?id=a2zt0000000GnywAAC&amp;status=Active" target="blank">https://www.privacyshield.gov/participant?id=a2zt0000000GnywAAC&amp;status=Active</a>).</p>
            <p>With the aid of Facebook Pixels, Facebook is able to determine our website users as a targets group to which ads can be displayed ('Facebook Ads"). We therefore use the Facebook Pixel to display our Facebook Ads only to those Facebook users who have also shown an interest in our website, or who demonstrate certain characteristics (e.g. interests in certain subjects or products, which are determined according to the websites visited), which we transmit to Facebook ( 'Custom Audiences").</p>
            <p>With the aid of the Facebook Pixel, we are also seeking to ensure that our Facebook Ads are in keeping with users" potential interests, rather than be an irritation. With the aid of the Facebook Pixel, we are also able to verify the effectiveness of Facebook ads for statistical and market research purposes, because we are able to see whether users are redirected to our website having clicked on a Facebook ad (known as conversion). The data is processed by Facebook in accordance with its policy on the use of data. Relevant general information on the display of Facebook Ads, Facebook's policy on the use of data: <a class="a_color text-decoration-underline" href="https://www.facebook.com/policy.php" target="_blank">https://www.facebook.com/policy.php</a>.</p>
            <p>Specialist information and details on Facebook Pixel and how it functions can be found in the help section of Facebook: <a href="#" class="a_color text-decoration-underline" target="_blank">https://www.facebook.com/business/help/651294705016616</a>. You can opt-out from your data be recorded by Facebook Pixel, and the use of your data for the display of Facebook Ads. Visit the page set up by Facebook and follow the instructions on usage-based advertising preferences in order to set the types of ads you see within Facebook: <a href="#" class="a_color text-decoration-underline" target="_blank">https://www.facebook.com/settings?tab=ads</a>.</p>
            <p>The settings are platform-independent, meaning they are applied to all devices, such as desktop computers or mobile devices. You may opt out of the use of cookies for reach measurement and advertising purposes via the deactivation page of the Network Advertising Initiative (<a class="a_color text-decoration-underline" href="https://optout.networkadvertising.org/" target="_blank">https://optout.networkadvertising.org/</a>) as well as the U.S. website (<a class="a_color text-decoration-underline" href="https://www.aboutads.info/choices" target="_blank">https://www.aboutads.info/choices</a>) or the European website (<a href="#" class="a_color text-decoration-underline" target="_blank">https://www.youronlinechoices.com/uk/your-ad-choices/</a>).</p>
            <i>Vimeo</i>
            <p>We may incorporate videos from the "Vimeo" platform operated by Vimeo Inc., Attention: Legal Department, 555 West 18th Street New York, New York 10011, USA. Privacy Policy: <a href="#" class="a_color text-decoration-underline" target="_blank">https://vimeo.com/privacy</a>. Please note that Vimeo can use Google Analytics, and refer to the Privacy Policy in this regard (<a href="#" class="a_color text-decoration-underline" target="_blank">https://www.google.com/policies/privacy</a>) as well as the opt-out options for Google Analytics (<a href="#" class="a_color text-decoration-underline" target="_blank">https://tools.google.com/dlpage/gaoptout?hl=de</a>) and the Google settings for the use of data for marketing purposes (<a href="#" class="a_color text-decoration-underline" target="_blank">https://adssettings.google.com/</a>).</p>
            <i>YouTube</i>
            <p>We include videos from the "YouTube" platform operated by Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA. Privacy Policy: <a href="#" class="a_color text-decoration-underline" target="_blank">https://www.google.com/policies/privacy/</a>, Opt-out: <a href="#" class="a_color text-decoration-underline" target="_blank">https://adssettings.google.com/authenticated</a>.</p>
            <i>Google Fonts</i>
            <p>We include fonts ("Google Fonts") from the provider Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA. Privacy Policy:<a href="#" class="a_color text-decoration-underline" target="_blank"> https://www.google.com/policies/privacy/</a>, Opt-out: <a href="#" class="a_color text-decoration-underline" target="_blank">https://adssettings.google.com/authenticated.</a></p>
            <i>Google ReCaptcha</i>
            <p>We have integrated integrates the bot recognition function ('ReCaptcha"), e.g. for information entered into online form, provided by Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA. Privacy Policy: <a href="#" class="a_color text-decoration-underline" target="_blank">https://www.google.com/policies/privacy/</a>, Opt-out: <a href="#" class="a_color text-decoration-underline" target="_blank">https://adssettings.google.com/authenticated</a>.</p>
            <i>Google Maps</i>
            <p>We have integrated maps from the "Google Maps" service provided by the provider Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA. The processed data can particularly include the IP addresses and location data of users, but which are not collected without the users" consent (generally obtained through the settings on their mobile devices). The data may processed in the United States of America. Privacy Policy: <a href="#" class="a_color text-decoration-underline" target="_blank">https://www.google.com/policies/privacy/</a>, Opt-out: <a href="#" class="a_color text-decoration-underline" target="_blank">https://adssettings.google.com/authenticated</a>.</p>
            <i>Instagram</i>
            <p>Our website may contain functions and content of the Instagram service, provided by Instagram Inc., 1601 Willow Road, Menlo Park, CA, 94025, USA. This may include content such as images, videos or texts and buttons which users can use to rate the appeal of the content, subscribe to the authors of the content or to our articles. If the users are members of the Instagram platform, Instagram can assign the accessing of the above content and functions to its users" profiles. Instagram privacy policy: <a href="#" class="a_color text-decoration-underline" target="_blank">https://instagram.com/about/legal/privacy/</a>.</p>
            <i>Hotjar</i>
            <p>This website uses the Hotjar service provided by Hotjar Limited (Level 2, St Julian's Business Centre, 3, Elia Zammit Street, St Julian's STJ 1000, Malta), for the purpose of conducting statistical analysis of visitor data. Hotjar is a service that analyses the interaction of randomly selected individual visitors, and the feedback from users of our website. This is performed using a combination or analytical and feedback tools, and the results are displayed in an anonymized manner. The data recorded in this manner, e.g. mouse movements and clicks, information about the operating system, browser, incoming and outgoing links, geographical origin and language settings as well as resolution and type of terminal device used, is collected with the aim of identifying potential areas for improvements in our website, so as to continually improve the user experience.</p>
            <p>If you would prefer that data not be recorded by Hotjar, you can use the Hotjar opt-out for this purpose (<a href="#" class="a_color text-decoration-underline" target="_blank">https://www.hotjar.com/legal/compliance/opt-out</a>). This gives you the option of deactivating or reactivating Hotjar"s data collection function. Note: Deleting cookies, visiting the website using your browser"s incognito/private browsing mode or using a different browser will prevent the collection of data.</p>
            <p>More details on Hotjar's privacy policy and how it collects what types of data is available at <a href="#" class="a_color text-decoration-underline" target="_blank">https://www.hotjar.com/legal/policies/privacy</a>.</p>
            <h6>13. Contact for data protection matters</h6>
            <p>For all queries concerning data protection law and data protection matters, please contact:</p>
            <ul class="list-unstyled mt-3 mb-3">
              <li>datenschutz@findmyhome.at</li>
              <li>FindMyHome.at GmbH - Die Immobilienwebsite</li>
              <li>Hutweidengasse 40 /Top 18</li>
              <li>1190 Vienna</li>
            </ul>
            <h6>14. Amendments to the Privacy Statement</h6>
            <p>Please consult the contents of our Privacy Policy regularly. We will amend the Privacy Policy as soon as this becomes necessary due to changes in the data processing performed by us. We shall inform you if such changes ever require any action on your part (such as issuing consent), or if any individual notification is necessary.</p>
          </div>
        </div>
      </div>
      <?php include 'footer.php' ?>
    </div>
  </section>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <script type="text/javascript" src="./assets/js/find_my_home.js"></script>
</body>
</html>